# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/realm/SwiftLint
  rev: "0.47.0"
  hooks:
    - id: swiftlint
      args: ["--reporter", "github-actions-logging"]
- repo: https://github.com/nicklockwood/SwiftFormat
  rev: "0.49.7"
  hooks:
    - id: swiftformat