name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: fwal/setup-swift@v1
      with:
        swift-version: "5.6"
    - name: Install dependencies
      run: brew install imagemagick@7
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v

  lint:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: fwal/setup-swift@v1
      with:
        swift-version: "5.6"
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v2.0.3
